/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "#ff6b35",
          light: "#ff8c5a",
          dark: "#e5521e",
          50: "#fff4ef",
          100: "#ffe3d4",
          500: "#ff6b35",
          600: "#e5521e",
        },
        dark: {
          bg: "#070708",
          surface: "#0f0f11",
          card: "#16161a",
          elevated: "#1e1e24",
          border: "#2a2a35",
          hover: "#252530",
        },
        light: {
          bg: "#f8f7f5",
          surface: "#ffffff",
          card: "#ffffff",
          elevated: "#f0eeeb",
          border: "#e5e2dd",
          hover: "#f5f3f0",
        },
        text: {
          primary: "#f5f4f2",
          secondary: "#a0a0b0",
          muted: "#5a5a6e",
        },
      },
      fontFamily: {
        sans: ["'Nunito'", "sans-serif"],
        display: ["'Clash Display'", "'Syne'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      animation: {
        "slide-up": "slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-down": "slideDown 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
        "fade-in": "fadeIn 0.3s ease",
        "scale-in": "scaleIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "shimmer": "shimmer 1.8s infinite",
        "pulse-soft": "pulseSoft 2s infinite",
        "float": "float 3s ease-in-out infinite",
        "bounce-dot": "bounceDot 1.2s infinite",
        "spin-slow": "spin 3s linear infinite",
        "wiggle": "wiggle 0.5s ease-in-out",
        "toast-in": "toastIn 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
        "progress": "progress 2s ease-in-out infinite",
      },
      keyframes: {
        slideUp: { from: { opacity: 0, transform: "translateY(20px)" }, to: { opacity: 1, transform: "translateY(0)" } },
        slideDown: { from: { opacity: 0, transform: "translateY(-20px)" }, to: { opacity: 1, transform: "translateY(0)" } },
        fadeIn: { from: { opacity: 0 }, to: { opacity: 1 } },
        scaleIn: { from: { opacity: 0, transform: "scale(0.92)" }, to: { opacity: 1, transform: "scale(1)" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        pulseSoft: { "0%, 100%": { opacity: 1 }, "50%": { opacity: 0.6 } },
        float: { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-8px)" } },
        bounceDot: { "0%, 80%, 100%": { transform: "scale(0)" }, "40%": { transform: "scale(1)" } },
        wiggle: { "0%, 100%": { transform: "rotate(-3deg)" }, "50%": { transform: "rotate(3deg)" } },
        toastIn: { from: { opacity: 0, transform: "translateX(100%) scale(0.8)" }, to: { opacity: 1, transform: "translateX(0) scale(1)" } },
        progress: { "0%": { width: "0%" }, "50%": { width: "70%" }, "100%": { width: "100%" } },
      },
      backdropBlur: { xs: "2px" },
      boxShadow: {
        "glow": "0 0 20px rgba(255, 107, 53, 0.3)",
        "glow-lg": "0 0 40px rgba(255, 107, 53, 0.4)",
        "card": "0 4px 24px rgba(0,0,0,0.12)",
        "card-hover": "0 12px 40px rgba(0,0,0,0.2)",
        "float": "0 20px 60px rgba(0,0,0,0.3)",
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
    },
  },
  plugins: [],
};