import express from "express";
import { placeOrder, getMyOrders, getOrderById, updateOrderStatus, getStoreOrders } from "../controllers/orderController.js";
import { protect, restrictTo } from "../middleware/authMiddleware.js";
const r = express.Router();
r.post("/", protect, restrictTo("customer"), placeOrder);
r.get("/my", protect, getMyOrders);
r.get("/:id", protect, getOrderById);
r.put("/:id/status", protect, restrictTo("store", "delivery"), updateOrderStatus);
r.get("/store/:storeId", protect, restrictTo("store"), getStoreOrders);
export default r;